debugh

diff --git a/.github/workflows/deploy-docker.yaml b/.github/workflows/deploy-docker.yaml
--- a/.github/workflows/deploy-docker.yaml
+++ b/.github/workflows/deploy-docker.yaml
@@ -28,15 +28,25 @@ jobs:
           echo "Latest release name: $latest_release"
           echo "LATEST_RELEASE_NAME=$latest_release" >> $GITHUB_ENV
 
-      - name: Use Latest Release Name
-        run: echo "The latest release is $LATEST_RELEASE_NAME"
+      - name: Print Environment Variables
+        run: |
+          echo "LATEST_RELEASE_NAME=$LATEST_RELEASE_NAME"
+          echo "CR_REGISTRY=$CR_REGISTRY"
 
       - name: Build docker image
         env:
           CR_REGISTRY: crpkb2sscjdrc12okn1d
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          # Check if LATEST_RELEASE_NAME is set correctly
+          if [ -z "$LATEST_RELEASE_NAME" ]; then
+            echo "Error: LATEST_RELEASE_NAME is empty."
+            exit 1
+          fi
+
+          # Build and push Docker images
           docker build -t cr.yandex/$CR_REGISTRY/app:$LATEST_RELEASE_NAME .
           docker build -t cr.yandex/$CR_REGISTRY/app:$LATEST_RELEASE_NAME_latest .
+          
           docker push cr.yandex/$CR_REGISTRY/app:$LATEST_RELEASE_NAME
           docker push cr.yandex/$CR_REGISTRY/app:$LATEST_RELEASE_NAME_latest
